name: Add to comments

on:
  issues:
    types: [labeled]
    
  workflow_dispatch:
    
jobs:
  if: ${{ github.event.label.name == 'Data Request'}}
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Issue
        uses: ActionsDesk/add-comment-action@master
        with:
           message: 'Welcome to the repository!'
        env:
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
